---
 - name: Configure in Remote Hosts
   hosts: all
   gather_facts: true
   become: yes
   vars:
     tomcat_port: 8284
   tasks:
    - name: Update repos
      apt:
        name: "*"
        state: latest
  
    - name: Installing OpenJDK
      apt:
        name: openjdk-8-jdk
    
  
    - name: Downloading tomcat
      get_url:
        url: "https://apachemirror.wuchna.com/tomcat/tomcat-9/v9.0.48/bin/apache-tomcat-9.0.48.tar.gz"
        dest: /usr/local
  
            
    - name: Extracting tomcat
      unarchive:
        src: "/usr/local/apache-tomcat-9.0.48.tar.gz"
        dest: /usr/local
        remote_src: yes
  
    - name: Renaming tomcat home
      command: mv /usr/local/apache-tomcat-9.0.48 /usr/local/tomcat
  
    - name: Changing port
      template:
        src: /root/server.xml.j2
        dest: /usr/local/tomcat/conf/server.xml
  
    - name: Updating users and role
      template:
        src: /root/tomcat-users.xml
        dest: /usr/local/tomcat/conf/tomcat-users.xml
 
    - name: Updating context xml restriction
      template:
        src: /root/context-manager.xml
        dest: /usr/local/tomcat/webapps/manager/META-INF/context.xml
 
    - name: Updating restriction for host manager context
      template:
        src: /root/context-host-manager.xml
        dest: /usr/local/tomcat/webapps/host-manager/META-INF/context.xml
 
    - name: Starting tomcat
      shell: nohup /usr/local/tomcat/bin/startup.sh &